# Module Numpy

Ce module est **indispensable** pour le calcul scientifique en Python. Il sert de base à de multiples autres modules  scientifiques (scipy, pandas, scikit-learn, matplotlib, etc).

Il permet de travailler sur des tableaux et des matrices à *n*-dimensions de manière optimisée, propose un tas de fonctions mathématiques et introduit la notion de **vectorisation**.

(Il est écrit majoritairement en C et Python pour accélérer la vitesse d'exécution).

Vous pouvez retrouver toute la documentation sur cette bibliothèque ici : https://numpy.org/doc/stable/user/index.html




In [1]:
import numpy

Par convention, vous remarquerez que la plupart du temps, on importe numpy en utilisant l'alias `np`

In [2]:
import numpy as np

## Nouvel Objet : le numpy array (ou *ND*-array)

Numpy introduit un nouveau type d'objet : le numpy array.

Les objets de type *array* correspondent à des tableaux à une ou plusieurs dimensions et permettent d'effectuer du calcul vectoriel. Par contre, ils ne peuvent contenir qu'un seul type de donnée (entier, flottant, etc).

Ils sont beaucoup plus efficaces que des listes pour le calcul (que ce soit en termes de mémoire ou de vitesse d'exécution).

**Remarque** : Il ne faut quasiment jamais utiliser de boucles sur les numpy arrays, préférez la vectorisation!


#### Comparaisons Liste Python vs Numpy arrays

| Liste Python                     | Numpy Array               |
|:--------------------------------:|:-------------------------:| 
| Typage dynamique                 | Typage fixé à la création |
| Redimensionnable                 | "taille fixe"             |
| dédié au stockage d'informations | dédié au calcul           |
| gourmand en mémoire              | léger en mémoire          |
| peu performant                   | très performant           |



### 1.1 Création d'arrays

La fonction `numpy.array()` convertit un objet séquentiel (comme une liste ou un tuple) en un objet de type array.

In [3]:
data = [12, 9, 16, 14, 8, 20]

vect = np.array(data)
print(type(vect))
vect

<class 'numpy.ndarray'>


array([12,  9, 16, 14,  8, 20])

### Matrices

In [4]:
mat = np.array([[1,2,3],[4,5,6]])
mat

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
mat3D = np.array([[[1, 2], [2, 3]], [[4, 5], [5, 6]]])
mat3D

array([[[1, 2],
        [2, 3]],

       [[4, 5],
        [5, 6]]])

Il existe plein d'autres façons de créer des numpy arrays :

  * `np.zeros()` : créé des arrays de 0
  * `np.ones()` : créé des arrays de 1
  * `np.arange()` : reproduit le fonctionnement de `range()`
  * `np.loadtxt()`: Charge des données depuis un fichier texte
  * etc (https://numpy.org/doc/stable/user/absolute_beginners.html#how-to-create-a-basic-array)
    

In [6]:
np.loadtxt("data.txt", comments="#")

array([[ 12. ,  31. ,   0. ],
       [  1. , 322. ,   6. ],
       [456. ,  12. , -12.5]])

### 1.3 Attributs

Voici quelques attributs intéressants pour décrire un objet array :

  * `.ndim` renvoie le nombre de dimensions (par exemple, 1 pour un vecteur et 2 pour une matrice).
  * `.shape` renvoie les dimensions sous forme d'un tuple. Dans le cas d'une matrice (array à deux dimensions), la première valeur du tuple correspond au nombre de lignes et la seconde au nombre de colonnes.
  * `.size` renvoie le nombre total d'éléments contenus dans l'array.


In [7]:
a = np.random.randint(10, size=5)       # 1D array (vecteur)
a

array([0, 3, 0, 0, 5])

In [8]:
b = np.random.randint(10, size=(3, 3))  # 2D array (matrice)
b

array([[5, 6, 8],
       [8, 6, 5],
       [5, 5, 0]])

In [9]:
print("Pour a: ndim = {} ; shape = {} ; size = {}".format(a.ndim, a.shape, a.size))
print("Pour b: ndim = {} ; shape = {} ; size = {}".format(b.ndim, b.shape, b.size))

Pour a: ndim = 1 ; shape = (5,) ; size = 5
Pour b: ndim = 2 ; shape = (3, 3) ; size = 9


## 2 Indexation et Slice

### 2.1 Indexation

Le fonctionnement des indexes et des *slices* en Numpy est identique à celui de Python pour les listes

**Arrays 1D**

In [10]:
a

array([0, 3, 0, 0, 5])

In [11]:
a[0]

0

In [12]:
a[-1]

5

Pour des matrices (arrays à 2 dimensions), le schéma ci-dessous s'applique :

<img src="https://python.sdv.univ-paris-diderot.fr/img/array_2D_lignes_colonnes.png" alt="array2D_index" style="width: 400px;"/>

On utilise la syntaxe `b[i, j]` qui renvoie l'élément à la **ligne** d'indice **i** et à la **colonne** d'indice **j**. Notez que NumPy suit la convention mathématiques des matrices, à savoir, on définit toujours un élément par sa ligne puis par sa colonne. 

**Arrays 2D**

In [13]:
b

array([[5, 6, 8],
       [8, 6, 5],
       [5, 5, 0]])

In [14]:
b[0,2]

8

In [15]:
b[-1,0]

5

In [16]:
b[-2,-3]

8

In [17]:
b[0]

array([5, 6, 8])

### 2.2 Slices sur les 1D-arrays

Fonctionnement aussi identique aux listes Python.

In [18]:
a

array([0, 3, 0, 0, 5])

In [19]:
a[2:]

array([0, 0, 5])

In [20]:
a[1:3]

array([3, 0])

### 2.3 Slices sur les 2D-arrays (et ND-arrays)

On applique la même logique mais axe par axe.

In [21]:
b

array([[5, 6, 8],
       [8, 6, 5],
       [5, 5, 0]])

In [22]:
b[1:, 2:] # 2 dernières lignes et dernière colonne

array([[5],
       [0]])

In [23]:
b[0,:] # (== b[1]) Que la 1ere ligne

array([5, 6, 8])

In [24]:
b[:,0] # Que la 1ère colonne

array([5, 8, 5])

## 3. Opérations sur les arrays

Le premier avantage de Numpy est sa rapidité de calcul sur les tableaux/matrices. Cela est du notamment à l'utilisation de la vectorisation.

### 3.1 Vectorisation

Le calcul vectoriel est le fait de pouvoir réaliser des opérations (mathématiques) simultanément sur tous les éléments d'un array (sans passer par des boucles !)



**Arrays 1D**

In [25]:
a

array([0, 3, 0, 0, 5])

In [26]:
a + 1

array([1, 4, 1, 1, 6])

In [27]:
a - 10

array([-10,  -7, -10, -10,  -5])

$-(\frac{1}{2} a +1)^2$

In [28]:
-(0.5*a + 1) ** 2

array([ -1.  ,  -6.25,  -1.  ,  -1.  , -12.25])

**Arrays 2D**

In [29]:
b

array([[5, 6, 8],
       [8, 6, 5],
       [5, 5, 0]])

In [30]:
b * 2

array([[10, 12, 16],
       [16, 12, 10],
       [10, 10,  0]])

Ce type de fonctionnalité  marche également entre des arrays. Numpy appelle cela le *broadcasting*

**Arrays 1D**

In [31]:
c = a + np.array([10,9,8,7,6])
print(a)
print(c)

[0 3 0 0 5]
[10 12  8  7 11]


**Arrays 2D (matrices)**


<img src="https://numpy.org/doc/stable/_images/np_matrix_arithmetic.png" alt="" style="width: 800px;"/>

[Source Doc Numpy](https://numpy.org/doc/stable/user/absolute_beginners.html#creating-matrices)

In [32]:
data = np.array([[1, 2], [3, 4]])
ones = np.array([[1, 1], [1, 1]])
data + ones

array([[2, 3],
       [4, 5]])

**Arrays 1D et 2D**

<img src="https://numpy.org/doc/stable/_images/np_matrix_broadcasting.png" alt="" style="width: 800px;"/>

[Source Doc Numpy](https://numpy.org/doc/stable/user/absolute_beginners.html#creating-matrices)

In [33]:
data = np.array([[1, 2], [3, 4],[5,6]])
ones_row = np.array([1, 1])
data + ones_row

array([[2, 3],
       [4, 5],
       [6, 7]])

### 3.2 Fonctions Mathématiques

In [34]:
a

array([0, 3, 0, 0, 5])

In [35]:
a.sum()

8

In [36]:
a.min()

0

In [37]:
a.std()

2.0591260281974

Il y a énormément de fonctions mathématiques disponible sous numpy :
 * trigonométrie (https://numpy.org/doc/stable/reference/routines.math.html#trigonometric-functions)
 * exposants et logarithmes (https://numpy.org/doc/stable/reference/routines.math.html#exponents-and-logarithms)
 * algèbre linéaire : produit vectoriel, produit matriciel, etc (https://numpy.org/doc/stable/reference/routines.linalg.html)
 * etc

## Exercice

 * Reprendre l'exercice 7.7.1 en utilisant `np.loadtxt()` et sans boucle!
 * Afficher la note minimale et maximale
 * Appliquer un bonificateur +1.5 à l'ensemble des notes et ré-afficher la nouvelle moyenne